import { useEffect } from 'react';
import { ArrowRight, CheckCircle2, CircleDot, Clock3, Flame, Inbox, Sparkles } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { useGetDashboardSummary } from '@workspace/api-client-react';
import { Badge, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '@/components/ui';

export function DashboardPage() {
  const summaryQuery = useGetDashboardSummary();
  const [, setLocation] = useLocation();
  useEffect(() => {
    const status = (summaryQuery.error as { status?: number } | null)?.status;
    if (status === 401 || status === 403) {
      localStorage.removeItem('support_token');
      setLocation('/login');
    }
  }, [summaryQuery.error, setLocation]);
  const summary = summaryQuery.data;
  const metrics = summary ? [{ label: 'All tickets', value: summary.total, icon: Inbox, tone: 'text-primary' }, { label: 'Open now', value: summary.open, icon: CircleDot, tone: 'text-accent-foreground' }, { label: 'In progress', value: summary.inProgress, icon: Clock3, tone: 'text-sky-700' }, { label: 'Resolved', value: summary.resolved, icon: CheckCircle2, tone: 'text-primary' }, { label: 'Critical', value: summary.critical, icon: Flame, tone: 'text-destructive' }] : [];
  return <div className="animate-rise"><PageHeader eyebrow="Monday, customer operations" title="Good morning, operator." detail="A quiet read on the queue, with the signals that deserve your attention first." action={<Link href="/tickets/new" data-testid="link-create-ticket-dashboard" className="inline-flex items-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-extrabold text-accent-foreground transition hover:brightness-105">Open a ticket <ArrowRight size={16} /></Link>} />
    {summaryQuery.isLoading ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[1, 2, 3, 4, 5].map((i) => <Skeleton key={i} className="h-28" />)}</div> : summaryQuery.isError ? <ErrorState onRetry={() => summaryQuery.refetch()} /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{metrics.map(({ label, value, icon: Icon, tone }, index) => <Card key={label} className={`animate-rise stagger-${Math.min(index + 1, 3)} p-4`}><div className="flex items-start justify-between"><span className="text-xs font-semibold text-muted-foreground">{label}</span><Icon size={16} className={tone} /></div><p data-testid={`metric-${label.toLowerCase().replace(/\s+/g, '-')}`} className="mt-5 font-mono-ui text-3xl tracking-[-.06em]">{value}</p></Card>)}</div>}
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-primary">Queue pulse</p><h2 className="mt-1 text-lg font-extrabold tracking-[-.03em]">Recent conversations</h2></div><Link href="/tickets" data-testid="link-view-all-tickets" className="flex items-center gap-1 text-xs font-bold text-primary hover:underline">View all <ArrowRight size={14} /></Link></div>{summary?.recent?.length ? <div>{summary.recent.map((ticket) => <Link href={`/tickets/${ticket.id}`} key={ticket.id} data-testid={`row-recent-ticket-${ticket.id}`} className="flex items-center gap-4 border-b border-border px-5 py-4 transition last:border-0 hover:bg-secondary/45"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-secondary text-xs font-extrabold text-primary">{ticket.customer?.name?.split(' ').map((part) => part[0]).join('').slice(0, 2) || 'CU'}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{ticket.subject}</p><p className="mt-1 text-xs text-muted-foreground">{ticket.customer?.name || 'Customer'} · {new Date(ticket.updatedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</p></div><Badge tone={ticket.priority === 'CRITICAL' ? 'red' : ticket.status === 'RESOLVED' ? 'teal' : 'neutral'}>{ticket.status.replace('_', ' ')}</Badge><ArrowRight size={15} className="text-muted-foreground" /></Link>)}</div> : <EmptyState title="No recent conversations" detail="New tickets will surface here as the queue moves." />}</Card><Card className="relative overflow-hidden bg-sidebar p-6 text-sidebar-foreground"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full border-[24px] border-sidebar-primary/10" /><div className="relative"><Sparkles size={18} className="text-sidebar-primary" /><p className="mt-7 font-mono-ui text-[10px] uppercase tracking-[.17em] text-sidebar-primary">AI desk note</p><h2 className="mt-3 max-w-xs text-2xl font-extrabold leading-tight tracking-[-.045em]">Intelligence should feel like a second set of eyes.</h2><p className="mt-4 max-w-xs text-sm leading-6 text-sidebar-foreground/60">Analyze a ticket to surface sentiment and a concise summary. Generate replies only from your grounded knowledge base.</p><Link href="/tickets" data-testid="link-open-ai-queue" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-sidebar-primary px-3.5 py-2.5 text-xs font-extrabold text-sidebar">Open AI queue <ArrowRight size={14} /></Link></div></Card></div>
  </div>;
}