import { useMemo, useState } from 'react';
import { BookOpen, CheckCircle2, ChevronRight, Database, FilePlus2, RefreshCw, Search, X } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetKnowledgeQueryKey, getListKnowledgeQueryKey, useCreateKnowledge, useGetKnowledge, useListKnowledge, useReindexKnowledge, type TicketCategory } from '@workspace/api-client-react';
import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '@/components/ui';

const categories = ['GENERAL', 'BILLING', 'TECHNICAL', 'ACCOUNT', 'SHIPPING', 'REFUND'] as const;
export function KnowledgePage() {
  const client = useQueryClient();
  const [search, setSearch] = useState('');
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [creating, setCreating] = useState(false);
  const params = useMemo(() => ({ search: search || undefined }), [search]);
  const query = useListKnowledge(params);
  const detail = useGetKnowledge(selectedId ?? 0, { query: { enabled: selectedId !== null, queryKey: getGetKnowledgeQueryKey(selectedId ?? 0) } });
  const create = useCreateKnowledge();
  const reindex = useReindexKnowledge();
  const docs = query.data || [];
  const submit = (data: { title: string; content: string; category: TicketCategory }) => create.mutate({ data }, { onSuccess: () => { client.invalidateQueries({ queryKey: getListKnowledgeQueryKey() }); setCreating(false); } });
  return <div className="animate-rise"><PageHeader eyebrow="Ground truth" title="Knowledge base" detail="The source of truth Gemini uses to keep replies useful, accurate, and close to your team’s voice." action={<Button variant="outline" loading={reindex.isPending} onClick={() => reindex.mutate(undefined, { onSuccess: () => client.invalidateQueries({ queryKey: getListKnowledgeQueryKey() }) })}><RefreshCw size={15} />Reindex embeddings</Button>} />
    <div className="mb-5 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div className="relative max-w-lg flex-1"><Search size={17} className="absolute left-3 top-3 text-muted-foreground" /><input data-testid="input-knowledge-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search documents" className="h-11 w-full rounded-lg border border-input bg-card pl-10 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /></div><Button onClick={() => setCreating(true)}><FilePlus2 size={15} />Add document</Button></div>
    {reindex.data && <p data-testid="status-reindex-success" className="mb-4 flex items-center gap-2 text-xs font-semibold text-primary"><CheckCircle2 size={15} />{reindex.data.succeeded} of {reindex.data.processed} documents are ready for Gemini.</p>}
    {query.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((i) => <Skeleton key={i} className="h-48" />)}</div> : query.isError ? <ErrorState onRetry={() => query.refetch()} /> : docs.length === 0 ? <EmptyState title="No source documents yet" detail="Add the policies, answers, and operational context your agents reach for every day." action={<Button onClick={() => setCreating(true)}>Add first document</Button>} /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{docs.map((doc) => <button key={doc.id} data-testid={`card-knowledge-${doc.id}`} onClick={() => setSelectedId(doc.id)} className="group text-left"><Card className="h-full p-5 transition duration-200 group-hover:-translate-y-0.5 group-hover:border-primary/45"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary"><BookOpen size={17} /></span><ChevronRight size={16} className="text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" /></div><h2 className="mt-5 line-clamp-2 text-base font-extrabold leading-6">{doc.title}</h2><p className="mt-2 line-clamp-3 text-xs leading-5 text-muted-foreground">{doc.content}</p><div className="mt-5 flex items-center justify-between"><Badge tone="teal">{doc.category}</Badge><span className="flex items-center gap-1.5 font-mono-ui text-[10px] uppercase tracking-[.08em] text-muted-foreground">{doc.hasEmbedding ? <><CheckCircle2 size={12} className="text-primary" />Indexed</> : <><Database size={12} />Needs index</>}</span></div></Card></button>)}</div>}
    {creating && <DocumentDialog pending={create.isPending} error={create.isError} onClose={() => setCreating(false)} onSubmit={submit} />}
    {selectedId !== null && <div className="fixed inset-0 z-50 flex items-center justify-center bg-sidebar/40 p-4" onClick={() => setSelectedId(null)}><div className="max-h-[85dvh] w-full max-w-2xl overflow-auto rounded-2xl border border-border bg-card shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between border-b border-border p-5"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-primary">Source document</p><h2 className="mt-1 text-xl font-extrabold">{detail.data?.title || 'Loading document'}</h2></div><button data-testid="button-close-knowledge-detail" onClick={() => setSelectedId(null)} className="rounded-lg p-2 text-muted-foreground hover:bg-secondary"><X size={17} /></button></div>{detail.isLoading ? <div className="space-y-3 p-6"><Skeleton className="h-4 w-3/4" /><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-5/6" /></div> : detail.data ? <div className="p-6"><div className="flex items-center gap-2"><Badge tone="teal">{detail.data.category}</Badge><span className="text-xs text-muted-foreground">{detail.data.hasEmbedding ? 'Available to Gemini' : 'Not yet indexed'}</span></div><p data-testid={`text-knowledge-content-${selectedId}`} className="mt-6 whitespace-pre-wrap text-sm leading-7 text-foreground/80">{detail.data.content}</p><p className="mt-7 font-mono-ui text-[10px] uppercase tracking-[.12em] text-muted-foreground">Updated {new Date(detail.data.updatedAt).toLocaleString()}</p></div> : <p className="p-6 text-sm text-muted-foreground">This document is no longer available.</p>}</div></div>}
  </div>;
}

function DocumentDialog({ pending, error, onClose, onSubmit }: { pending: boolean; error: boolean; onClose: () => void; onSubmit: (data: { title: string; content: string; category: TicketCategory }) => void }) {
  const [form, setForm] = useState({ title: '', content: '', category: 'GENERAL' as TicketCategory });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-sidebar/40 p-4"><div className="w-full max-w-xl rounded-2xl border border-border bg-card shadow-2xl"><div className="flex items-center justify-between border-b border-border p-5"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-primary">Add source</p><h2 className="mt-1 text-xl font-extrabold">New knowledge document</h2></div><button data-testid="button-close-create-knowledge" onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-secondary"><X size={17} /></button></div><form onSubmit={(e) => { e.preventDefault(); onSubmit(form); }} className="space-y-4 p-5"><label className="block text-xs font-bold">Title<input data-testid="input-knowledge-title" required minLength={3} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Refund policy, Q2" className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-primary" /></label><label className="block text-xs font-bold">Content<textarea data-testid="input-knowledge-content" required minLength={20} rows={7} value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder="Write the policy or answer agents should trust..." className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-3 text-sm leading-6 outline-none focus:border-primary" /></label><label className="block text-xs font-bold">Category<select data-testid="select-knowledge-category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as TicketCategory })} className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-primary">{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>{error && <p className="text-xs font-semibold text-destructive">Could not save this document. Please try again.</p>}<div className="flex justify-end gap-3 border-t border-border pt-4"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button type="submit" loading={pending}>Save document</Button></div></form></div></div>;
}