import { useMemo, useState } from 'react';
import { ArrowRight, Filter, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { useCreateTicket, useListTickets, getListTicketsQueryKey, type TicketCategory, type TicketPriority } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '@/components/ui';

const categories = ['GENERAL', 'BILLING', 'TECHNICAL', 'ACCOUNT', 'SHIPPING', 'REFUND'] as const;
const priorities = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const;
const statuses = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'] as const;

export function TicketsPage() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [priority, setPriority] = useState('');
  const params = useMemo(() => ({ search: search || undefined, status: status ? status as typeof statuses[number] : undefined, priority: priority ? priority as typeof priorities[number] : undefined }), [search, status, priority]);
  const query = useListTickets(params);
  const tickets = query.data || [];
  return <div className="animate-rise"><PageHeader eyebrow="Work queue" title="Tickets" detail="Find the conversation, read the signal, and keep the next action visible." action={<Link href="/tickets/new" data-testid="link-create-ticket" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-extrabold text-primary-foreground transition hover:brightness-110"><Plus size={16} />New ticket</Link>} />
    <Card className="mb-5 p-3"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-muted-foreground" /><input data-testid="input-ticket-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search subject, customer, or description" className="h-11 w-full rounded-lg border border-input bg-background pl-10 pr-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /></div><div className="flex flex-wrap gap-2"><select data-testid="select-ticket-status" value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-lg border border-input bg-background px-3 text-xs font-bold outline-none"><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{item.replace('_', ' ')}</option>)}</select><select data-testid="select-ticket-priority" value={priority} onChange={(e) => setPriority(e.target.value)} className="h-11 rounded-lg border border-input bg-background px-3 text-xs font-bold outline-none"><option value="">All priority</option>{priorities.map((item) => <option key={item} value={item}>{item}</option>)}</select><button data-testid="button-clear-ticket-filters" onClick={() => { setSearch(''); setStatus(''); setPriority(''); }} className="inline-flex h-11 items-center gap-2 rounded-lg border border-border bg-card px-3 text-xs font-bold text-muted-foreground hover:bg-secondary"><Filter size={15} />Clear</button></div></div></Card>
    {query.isLoading ? <Card className="space-y-3 p-5">{[1, 2, 3, 4].map((i) => <Skeleton key={i} className="h-16" />)}</Card> : query.isError ? <ErrorState onRetry={() => query.refetch()} /> : tickets.length === 0 ? <EmptyState title="The queue is clear" detail={search || status || priority ? 'No ticket matches these filters.' : 'When customers reach out, their conversations will land here.'} action={<Link href="/tickets/new" data-testid="link-empty-new-ticket" className="text-sm font-bold text-primary hover:underline">Create the first ticket</Link>} /> : <Card className="overflow-hidden"><div className="hidden grid-cols-[minmax(240px,1fr)_170px_130px_150px_30px] gap-4 border-b border-border bg-secondary/35 px-5 py-3 font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground md:grid"><span>Conversation</span><span>Category</span><span>Priority</span><span>Status</span><span /></div>{tickets.map((ticket) => <Link href={`/tickets/${ticket.id}`} key={ticket.id} data-testid={`row-ticket-${ticket.id}`} className="grid grid-cols-1 gap-3 border-b border-border px-5 py-4 transition last:border-0 hover:bg-secondary/35 md:grid-cols-[minmax(240px,1fr)_170px_130px_150px_30px] md:items-center md:gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-mono-ui text-[10px] text-muted-foreground">#{String(ticket.id).padStart(4, '0')}</span>{ticket.sentiment === 'URGENT' && <Badge tone="red">urgent</Badge>}</div><p className="mt-1 truncate text-sm font-extrabold">{ticket.subject}</p><p className="mt-1 truncate text-xs text-muted-foreground">{ticket.customer?.name || 'Customer'} · {new Date(ticket.updatedAt).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</p></div><div><span className="text-xs font-semibold text-muted-foreground md:hidden">Category · </span><span className="text-xs font-bold">{ticket.category}</span></div><div><span className="text-xs font-semibold text-muted-foreground md:hidden">Priority · </span><Badge tone={ticket.priority === 'CRITICAL' ? 'red' : ticket.priority === 'HIGH' ? 'orange' : 'neutral'}>{ticket.priority}</Badge></div><div><Badge tone={ticket.status === 'RESOLVED' || ticket.status === 'CLOSED' ? 'teal' : ticket.status === 'IN_PROGRESS' ? 'blue' : 'neutral'}>{ticket.status.replace('_', ' ')}</Badge></div><ArrowRight size={16} className="hidden text-muted-foreground md:block" /></Link>)}</Card>}
  </div>;
}

export function NewTicketPage() {
  const [, setLocation] = useLocation();
  const client = useQueryClient();
  const create = useCreateTicket();
  const [form, setForm] = useState({ subject: '', description: '', category: 'GENERAL' as TicketCategory, priority: 'MEDIUM' as TicketPriority });
  const submit = (e: React.FormEvent) => { e.preventDefault(); create.mutate({ data: form }, { onSuccess: (ticket) => { client.invalidateQueries({ queryKey: getListTicketsQueryKey() }); setLocation(`/tickets/${ticket.id}`); } }); };
  return <div className="mx-auto max-w-3xl animate-rise"><PageHeader eyebrow="New conversation" title="Open a ticket" detail="Capture enough context for the next person to help without asking the customer twice." /><Card className="p-5 md:p-7"><form onSubmit={submit} className="space-y-6"><div><label className="mb-2 block text-xs font-bold">Subject</label><input data-testid="input-new-ticket-subject" required minLength={3} value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} placeholder="What does the customer need help with?" className="h-12 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /></div><div><label className="mb-2 block text-xs font-bold">Description</label><textarea data-testid="input-new-ticket-description" required minLength={10} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Add the customer’s words, context, and what has already been tried." rows={8} className="w-full resize-y rounded-lg border border-input bg-background px-3 py-3 text-sm leading-6 outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Category<select data-testid="select-new-ticket-category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as TicketCategory })} className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm font-medium outline-none focus:border-primary">{categories.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label className="text-xs font-bold">Priority<select data-testid="select-new-ticket-priority" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as TicketPriority })} className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm font-medium outline-none focus:border-primary">{priorities.map((item) => <option value={item} key={item}>{item}</option>)}</select></label></div>{create.isError && <p data-testid="status-create-ticket-error" className="rounded-lg bg-destructive/8 p-3 text-xs font-semibold text-destructive">We could not create this ticket. Check the fields and try again.</p>}<div className="flex justify-end gap-3 border-t border-border pt-5"><Link href="/tickets" data-testid="link-cancel-ticket" className="inline-flex h-10 items-center rounded-lg px-4 text-sm font-bold text-muted-foreground hover:bg-secondary">Cancel</Link><Button type="submit" loading={create.isPending}>Create ticket <ArrowRight size={15} /></Button></div></form></Card></div>;
}